// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event/v1/event.proto

package io.nitric.proto.event.v1;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_event_v1_EventPublishRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_event_v1_EventPublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_event_v1_EventPublishResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_event_v1_EventPublishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_event_v1_TopicListRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_event_v1_TopicListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_event_v1_TopicListResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_event_v1_TopicListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_event_v1_NitricTopic_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_event_v1_NitricTopic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_event_v1_NitricEvent_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_event_v1_NitricEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024event/v1/event.proto\022\017nitric.event.v1\032" +
      "\034google/protobuf/struct.proto\"Q\n\023EventPu" +
      "blishRequest\022\r\n\005topic\030\001 \001(\t\022+\n\005event\030\002 \001" +
      "(\0132\034.nitric.event.v1.NitricEvent\"\"\n\024Even" +
      "tPublishResponse\022\n\n\002id\030\001 \001(\t\"\022\n\020TopicLis" +
      "tRequest\"A\n\021TopicListResponse\022,\n\006topics\030" +
      "\001 \003(\0132\034.nitric.event.v1.NitricTopic\"\033\n\013N" +
      "itricTopic\022\014\n\004name\030\001 \001(\t\"Y\n\013NitricEvent\022" +
      "\n\n\002id\030\001 \001(\t\022\024\n\014payload_type\030\002 \001(\t\022(\n\007pay" +
      "load\030\003 \001(\0132\027.google.protobuf.Struct2_\n\005E" +
      "vent\022V\n\007Publish\022$.nitric.event.v1.EventP" +
      "ublishRequest\032%.nitric.event.v1.EventPub" +
      "lishResponse2V\n\005Topic\022M\n\004List\022!.nitric.e" +
      "vent.v1.TopicListRequest\032\".nitric.event." +
      "v1.TopicListResponseBb\n\030io.nitric.proto." +
      "event.v1B\006EventsP\001Z\014nitric/v1;v1\252\002\025Nitri" +
      "c.Proto.Event.v1\312\002\025Nitric\\Proto\\Event\\V1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_nitric_event_v1_EventPublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nitric_event_v1_EventPublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_event_v1_EventPublishRequest_descriptor,
        new java.lang.String[] { "Topic", "Event", });
    internal_static_nitric_event_v1_EventPublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nitric_event_v1_EventPublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_event_v1_EventPublishResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_nitric_event_v1_TopicListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nitric_event_v1_TopicListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_event_v1_TopicListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_nitric_event_v1_TopicListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nitric_event_v1_TopicListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_event_v1_TopicListResponse_descriptor,
        new java.lang.String[] { "Topics", });
    internal_static_nitric_event_v1_NitricTopic_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nitric_event_v1_NitricTopic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_event_v1_NitricTopic_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_nitric_event_v1_NitricEvent_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nitric_event_v1_NitricEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_event_v1_NitricEvent_descriptor,
        new java.lang.String[] { "Id", "PayloadType", "Payload", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
