// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event/v1/event.proto

package io.nitric.proto.event.v1;

public interface EventPublishResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.event.v1.EventPublishResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the published message
   * When an id was not supplied
   * one should be automatically generated
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The id of the published message
   * When an id was not supplied
   * one should be automatically generated
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
