// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event/v1/event.proto

package io.nitric.proto.event.v1;

public interface NitricEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.event.v1.NitricEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A Unique ID for the Nitric Event
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * A Unique ID for the Nitric Event
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * A content hint for the events payload
   * </pre>
   *
   * <code>string payload_type = 2;</code>
   * @return The payloadType.
   */
  java.lang.String getPayloadType();
  /**
   * <pre>
   * A content hint for the events payload
   * </pre>
   *
   * <code>string payload_type = 2;</code>
   * @return The bytes for payloadType.
   */
  com.google.protobuf.ByteString
      getPayloadTypeBytes();

  /**
   * <pre>
   * The payload of the event
   * </pre>
   *
   * <code>.google.protobuf.Struct payload = 3;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <pre>
   * The payload of the event
   * </pre>
   *
   * <code>.google.protobuf.Struct payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.Struct getPayload();
  /**
   * <pre>
   * The payload of the event
   * </pre>
   *
   * <code>.google.protobuf.Struct payload = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getPayloadOrBuilder();
}
