// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event/v1/event.proto

package io.nitric.proto.event.v1;

public interface TopicListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.event.v1.TopicListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The list of found topics
   * </pre>
   *
   * <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
   */
  java.util.List<io.nitric.proto.event.v1.NitricTopic>
      getTopicsList();
  /**
   * <pre>
   * The list of found topics
   * </pre>
   *
   * <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
   */
  io.nitric.proto.event.v1.NitricTopic getTopics(int index);
  /**
   * <pre>
   * The list of found topics
   * </pre>
   *
   * <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
   */
  int getTopicsCount();
  /**
   * <pre>
   * The list of found topics
   * </pre>
   *
   * <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
   */
  java.util.List<? extends io.nitric.proto.event.v1.NitricTopicOrBuilder>
      getTopicsOrBuilderList();
  /**
   * <pre>
   * The list of found topics
   * </pre>
   *
   * <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
   */
  io.nitric.proto.event.v1.NitricTopicOrBuilder getTopicsOrBuilder(
      int index);
}
