// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv/v1/kv.proto

package io.nitric.proto.kv.v1;

public interface KeyValueQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.kv.v1.KeyValueQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The query from collection
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The collection.
   */
  java.lang.String getCollection();
  /**
   * <pre>
   * The query from collection
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The bytes for collection.
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <pre>
   * The query expressions
   * </pre>
   *
   * <code>repeated .nitric.kv.v1.KeyValueQueryRequest.Expression expressions = 2;</code>
   */
  java.util.List<io.nitric.proto.kv.v1.KeyValueQueryRequest.Expression>
      getExpressionsList();
  /**
   * <pre>
   * The query expressions
   * </pre>
   *
   * <code>repeated .nitric.kv.v1.KeyValueQueryRequest.Expression expressions = 2;</code>
   */
  io.nitric.proto.kv.v1.KeyValueQueryRequest.Expression getExpressions(int index);
  /**
   * <pre>
   * The query expressions
   * </pre>
   *
   * <code>repeated .nitric.kv.v1.KeyValueQueryRequest.Expression expressions = 2;</code>
   */
  int getExpressionsCount();
  /**
   * <pre>
   * The query expressions
   * </pre>
   *
   * <code>repeated .nitric.kv.v1.KeyValueQueryRequest.Expression expressions = 2;</code>
   */
  java.util.List<? extends io.nitric.proto.kv.v1.KeyValueQueryRequest.ExpressionOrBuilder>
      getExpressionsOrBuilderList();
  /**
   * <pre>
   * The query expressions
   * </pre>
   *
   * <code>repeated .nitric.kv.v1.KeyValueQueryRequest.Expression expressions = 2;</code>
   */
  io.nitric.proto.kv.v1.KeyValueQueryRequest.ExpressionOrBuilder getExpressionsOrBuilder(
      int index);

  /**
   * <pre>
   * The query fetch limit
   * </pre>
   *
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   * The query paging continuation token
   * </pre>
   *
   * <code>.google.protobuf.Struct pagingToken = 4;</code>
   * @return Whether the pagingToken field is set.
   */
  boolean hasPagingToken();
  /**
   * <pre>
   * The query paging continuation token
   * </pre>
   *
   * <code>.google.protobuf.Struct pagingToken = 4;</code>
   * @return The pagingToken.
   */
  com.google.protobuf.Struct getPagingToken();
  /**
   * <pre>
   * The query paging continuation token
   * </pre>
   *
   * <code>.google.protobuf.Struct pagingToken = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getPagingTokenOrBuilder();
}
