// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv/v1/kv.proto

package io.nitric.proto.kv.v1;

/**
 * Protobuf type {@code nitric.kv.v1.KeyValueQueryResponse}
 */
public final class KeyValueQueryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nitric.kv.v1.KeyValueQueryResponse)
    KeyValueQueryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KeyValueQueryResponse.newBuilder() to construct.
  private KeyValueQueryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KeyValueQueryResponse() {
    values_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KeyValueQueryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KeyValueQueryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              values_ = new java.util.ArrayList<com.google.protobuf.Struct>();
              mutable_bitField0_ |= 0x00000001;
            }
            values_.add(
                input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              pagingToken_ = com.google.protobuf.MapField.newMapField(
                  PagingTokenDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, io.nitric.proto.kv.v1.Key>
            pagingToken__ = input.readMessage(
                PagingTokenDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            pagingToken_.getMutableMap().put(
                pagingToken__.getKey(), pagingToken__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        values_ = java.util.Collections.unmodifiableList(values_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nitric.proto.kv.v1.KeyValues.internal_static_nitric_kv_v1_KeyValueQueryResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetPagingToken();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nitric.proto.kv.v1.KeyValues.internal_static_nitric_kv_v1_KeyValueQueryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nitric.proto.kv.v1.KeyValueQueryResponse.class, io.nitric.proto.kv.v1.KeyValueQueryResponse.Builder.class);
  }

  public static final int VALUES_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.Struct> values_;
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .google.protobuf.Struct values = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Struct> getValuesList() {
    return values_;
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .google.protobuf.Struct values = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.StructOrBuilder>
      getValuesOrBuilderList() {
    return values_;
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .google.protobuf.Struct values = 1;</code>
   */
  @java.lang.Override
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .google.protobuf.Struct values = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Struct getValues(int index) {
    return values_.get(index);
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .google.protobuf.Struct values = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getValuesOrBuilder(
      int index) {
    return values_.get(index);
  }

  public static final int PAGINGTOKEN_FIELD_NUMBER = 2;
  private static final class PagingTokenDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.nitric.proto.kv.v1.Key> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.nitric.proto.kv.v1.Key>newDefaultInstance(
                io.nitric.proto.kv.v1.KeyValues.internal_static_nitric_kv_v1_KeyValueQueryResponse_PagingTokenEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.nitric.proto.kv.v1.Key.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, io.nitric.proto.kv.v1.Key> pagingToken_;
  private com.google.protobuf.MapField<java.lang.String, io.nitric.proto.kv.v1.Key>
  internalGetPagingToken() {
    if (pagingToken_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PagingTokenDefaultEntryHolder.defaultEntry);
    }
    return pagingToken_;
  }

  public int getPagingTokenCount() {
    return internalGetPagingToken().getMap().size();
  }
  /**
   * <pre>
   * The query paging continuation token, when not null further results are available
   * </pre>
   *
   * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
   */

  @java.lang.Override
  public boolean containsPagingToken(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetPagingToken().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPagingTokenMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> getPagingToken() {
    return getPagingTokenMap();
  }
  /**
   * <pre>
   * The query paging continuation token, when not null further results are available
   * </pre>
   *
   * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> getPagingTokenMap() {
    return internalGetPagingToken().getMap();
  }
  /**
   * <pre>
   * The query paging continuation token, when not null further results are available
   * </pre>
   *
   * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
   */
  @java.lang.Override

  public io.nitric.proto.kv.v1.Key getPagingTokenOrDefault(
      java.lang.String key,
      io.nitric.proto.kv.v1.Key defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> map =
        internalGetPagingToken().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * The query paging continuation token, when not null further results are available
   * </pre>
   *
   * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
   */
  @java.lang.Override

  public io.nitric.proto.kv.v1.Key getPagingTokenOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> map =
        internalGetPagingToken().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < values_.size(); i++) {
      output.writeMessage(1, values_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPagingToken(),
        PagingTokenDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < values_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, values_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, io.nitric.proto.kv.v1.Key> entry
         : internalGetPagingToken().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.nitric.proto.kv.v1.Key>
      pagingToken__ = PagingTokenDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pagingToken__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nitric.proto.kv.v1.KeyValueQueryResponse)) {
      return super.equals(obj);
    }
    io.nitric.proto.kv.v1.KeyValueQueryResponse other = (io.nitric.proto.kv.v1.KeyValueQueryResponse) obj;

    if (!getValuesList()
        .equals(other.getValuesList())) return false;
    if (!internalGetPagingToken().equals(
        other.internalGetPagingToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    if (!internalGetPagingToken().getMap().isEmpty()) {
      hash = (37 * hash) + PAGINGTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPagingToken().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.kv.v1.KeyValueQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nitric.proto.kv.v1.KeyValueQueryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nitric.kv.v1.KeyValueQueryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nitric.kv.v1.KeyValueQueryResponse)
      io.nitric.proto.kv.v1.KeyValueQueryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nitric.proto.kv.v1.KeyValues.internal_static_nitric_kv_v1_KeyValueQueryResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetPagingToken();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutablePagingToken();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nitric.proto.kv.v1.KeyValues.internal_static_nitric_kv_v1_KeyValueQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nitric.proto.kv.v1.KeyValueQueryResponse.class, io.nitric.proto.kv.v1.KeyValueQueryResponse.Builder.class);
    }

    // Construct using io.nitric.proto.kv.v1.KeyValueQueryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValuesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        valuesBuilder_.clear();
      }
      internalGetMutablePagingToken().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nitric.proto.kv.v1.KeyValues.internal_static_nitric_kv_v1_KeyValueQueryResponse_descriptor;
    }

    @java.lang.Override
    public io.nitric.proto.kv.v1.KeyValueQueryResponse getDefaultInstanceForType() {
      return io.nitric.proto.kv.v1.KeyValueQueryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.nitric.proto.kv.v1.KeyValueQueryResponse build() {
      io.nitric.proto.kv.v1.KeyValueQueryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nitric.proto.kv.v1.KeyValueQueryResponse buildPartial() {
      io.nitric.proto.kv.v1.KeyValueQueryResponse result = new io.nitric.proto.kv.v1.KeyValueQueryResponse(this);
      int from_bitField0_ = bitField0_;
      if (valuesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
      } else {
        result.values_ = valuesBuilder_.build();
      }
      result.pagingToken_ = internalGetPagingToken();
      result.pagingToken_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nitric.proto.kv.v1.KeyValueQueryResponse) {
        return mergeFrom((io.nitric.proto.kv.v1.KeyValueQueryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nitric.proto.kv.v1.KeyValueQueryResponse other) {
      if (other == io.nitric.proto.kv.v1.KeyValueQueryResponse.getDefaultInstance()) return this;
      if (valuesBuilder_ == null) {
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
      } else {
        if (!other.values_.isEmpty()) {
          if (valuesBuilder_.isEmpty()) {
            valuesBuilder_.dispose();
            valuesBuilder_ = null;
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
            valuesBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValuesFieldBuilder() : null;
          } else {
            valuesBuilder_.addAllMessages(other.values_);
          }
        }
      }
      internalGetMutablePagingToken().mergeFrom(
          other.internalGetPagingToken());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.nitric.proto.kv.v1.KeyValueQueryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.nitric.proto.kv.v1.KeyValueQueryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.Struct> values_ =
      java.util.Collections.emptyList();
    private void ensureValuesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        values_ = new java.util.ArrayList<com.google.protobuf.Struct>(values_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> valuesBuilder_;

    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public java.util.List<com.google.protobuf.Struct> getValuesList() {
      if (valuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(values_);
      } else {
        return valuesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public int getValuesCount() {
      if (valuesBuilder_ == null) {
        return values_.size();
      } else {
        return valuesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public com.google.protobuf.Struct getValues(int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);
      } else {
        return valuesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder setValues(
        int index, com.google.protobuf.Struct value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder setValues(
        int index, com.google.protobuf.Struct.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.set(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder addValues(com.google.protobuf.Struct value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder addValues(
        int index, com.google.protobuf.Struct value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(index, value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder addValues(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder addValues(
        int index, com.google.protobuf.Struct.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder addAllValues(
        java.lang.Iterable<? extends com.google.protobuf.Struct> values) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
      } else {
        valuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder clearValues() {
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        valuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public Builder removeValues(int index) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.remove(index);
        onChanged();
      } else {
        valuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public com.google.protobuf.Struct.Builder getValuesBuilder(
        int index) {
      return getValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public com.google.protobuf.StructOrBuilder getValuesOrBuilder(
        int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);  } else {
        return valuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public java.util.List<? extends com.google.protobuf.StructOrBuilder>
         getValuesOrBuilderList() {
      if (valuesBuilder_ != null) {
        return valuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(values_);
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public com.google.protobuf.Struct.Builder addValuesBuilder() {
      return getValuesFieldBuilder().addBuilder(
          com.google.protobuf.Struct.getDefaultInstance());
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public com.google.protobuf.Struct.Builder addValuesBuilder(
        int index) {
      return getValuesFieldBuilder().addBuilder(
          index, com.google.protobuf.Struct.getDefaultInstance());
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .google.protobuf.Struct values = 1;</code>
     */
    public java.util.List<com.google.protobuf.Struct.Builder>
         getValuesBuilderList() {
      return getValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>
        getValuesFieldBuilder() {
      if (valuesBuilder_ == null) {
        valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                values_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      return valuesBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, io.nitric.proto.kv.v1.Key> pagingToken_;
    private com.google.protobuf.MapField<java.lang.String, io.nitric.proto.kv.v1.Key>
    internalGetPagingToken() {
      if (pagingToken_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PagingTokenDefaultEntryHolder.defaultEntry);
      }
      return pagingToken_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.nitric.proto.kv.v1.Key>
    internalGetMutablePagingToken() {
      onChanged();;
      if (pagingToken_ == null) {
        pagingToken_ = com.google.protobuf.MapField.newMapField(
            PagingTokenDefaultEntryHolder.defaultEntry);
      }
      if (!pagingToken_.isMutable()) {
        pagingToken_ = pagingToken_.copy();
      }
      return pagingToken_;
    }

    public int getPagingTokenCount() {
      return internalGetPagingToken().getMap().size();
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */

    @java.lang.Override
    public boolean containsPagingToken(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPagingToken().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPagingTokenMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> getPagingToken() {
      return getPagingTokenMap();
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> getPagingTokenMap() {
      return internalGetPagingToken().getMap();
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */
    @java.lang.Override

    public io.nitric.proto.kv.v1.Key getPagingTokenOrDefault(
        java.lang.String key,
        io.nitric.proto.kv.v1.Key defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> map =
          internalGetPagingToken().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */
    @java.lang.Override

    public io.nitric.proto.kv.v1.Key getPagingTokenOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> map =
          internalGetPagingToken().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPagingToken() {
      internalGetMutablePagingToken().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */

    public Builder removePagingToken(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePagingToken().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key>
    getMutablePagingToken() {
      return internalGetMutablePagingToken().getMutableMap();
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */
    public Builder putPagingToken(
        java.lang.String key,
        io.nitric.proto.kv.v1.Key value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePagingToken().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * The query paging continuation token, when not null further results are available
     * </pre>
     *
     * <code>map&lt;string, .nitric.kv.v1.Key&gt; pagingToken = 2;</code>
     */

    public Builder putAllPagingToken(
        java.util.Map<java.lang.String, io.nitric.proto.kv.v1.Key> values) {
      internalGetMutablePagingToken().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nitric.kv.v1.KeyValueQueryResponse)
  }

  // @@protoc_insertion_point(class_scope:nitric.kv.v1.KeyValueQueryResponse)
  private static final io.nitric.proto.kv.v1.KeyValueQueryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nitric.proto.kv.v1.KeyValueQueryResponse();
  }

  public static io.nitric.proto.kv.v1.KeyValueQueryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KeyValueQueryResponse>
      PARSER = new com.google.protobuf.AbstractParser<KeyValueQueryResponse>() {
    @java.lang.Override
    public KeyValueQueryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KeyValueQueryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KeyValueQueryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KeyValueQueryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nitric.proto.kv.v1.KeyValueQueryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

