// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv/v1/kv.proto

package io.nitric.proto.kv.v1;

public interface KeyValuePutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.kv.v1.KeyValuePutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The collection containing the existing keyValue to be inserted or updated.
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The collection.
   */
  java.lang.String getCollection();
  /**
   * <pre>
   * The collection containing the existing keyValue to be inserted or updated.
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The bytes for collection.
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <pre>
   * The unique key of the keyValue to put
   * </pre>
   *
   * <code>.google.protobuf.Struct key = 2;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <pre>
   * The unique key of the keyValue to put
   * </pre>
   *
   * <code>.google.protobuf.Struct key = 2;</code>
   * @return The key.
   */
  com.google.protobuf.Struct getKey();
  /**
   * <pre>
   * The unique key of the keyValue to put
   * </pre>
   *
   * <code>.google.protobuf.Struct key = 2;</code>
   */
  com.google.protobuf.StructOrBuilder getKeyOrBuilder();

  /**
   * <pre>
   * The top level attributes to put (optional)
   * </pre>
   *
   * <code>.google.protobuf.Struct attributes = 3;</code>
   * @return Whether the attributes field is set.
   */
  boolean hasAttributes();
  /**
   * <pre>
   * The top level attributes to put (optional)
   * </pre>
   *
   * <code>.google.protobuf.Struct attributes = 3;</code>
   * @return The attributes.
   */
  com.google.protobuf.Struct getAttributes();
  /**
   * <pre>
   * The top level attributes to put (optional)
   * </pre>
   *
   * <code>.google.protobuf.Struct attributes = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getAttributesOrBuilder();

  /**
   * <pre>
   * A simple JSON object
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 4;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * A simple JSON object
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 4;</code>
   * @return The value.
   */
  com.google.protobuf.Struct getValue();
  /**
   * <pre>
   * A simple JSON object
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getValueOrBuilder();
}
