// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv/v1/kv.proto

package io.nitric.proto.kv.v1;

public interface KeyValueGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.kv.v1.KeyValueGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The retrieved value
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * The retrieved value
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.Struct getValue();
  /**
   * <pre>
   * The retrieved value
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 1;</code>
   */
  com.google.protobuf.StructOrBuilder getValueOrBuilder();
}
