// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv/v1/kv.proto

package io.nitric.proto.kv.v1;

public interface KeyValuePutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.kv.v1.KeyValuePutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The collection containing the existing keyValue to be inserted or updated.
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The collection.
   */
  java.lang.String getCollection();
  /**
   * <pre>
   * The collection containing the existing keyValue to be inserted or updated.
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The bytes for collection.
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <pre>
   * The unique key of the keyValue to put
   * </pre>
   *
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <pre>
   * The unique key of the keyValue to put
   * </pre>
   *
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * A simple JSON object
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * A simple JSON object
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 3;</code>
   * @return The value.
   */
  com.google.protobuf.Struct getValue();
  /**
   * <pre>
   * A simple JSON object
   * </pre>
   *
   * <code>.google.protobuf.Struct value = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getValueOrBuilder();
}
