// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv/v1/kv.proto

package io.nitric.proto.kv.v1;

public interface KeyValueGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.kv.v1.KeyValueGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The collection to retrieve the keyValue from
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The collection.
   */
  java.lang.String getCollection();
  /**
   * <pre>
   * The collection to retrieve the keyValue from
   * </pre>
   *
   * <code>string collection = 1;</code>
   * @return The bytes for collection.
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <pre>
   * The unique key of the keyValue to retrieve
   * </pre>
   *
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <pre>
   * The unique key of the keyValue to retrieve
   * </pre>
   *
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
