// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: document/v1/document.proto

package io.nitric.proto.document.v1;

/**
 * Protobuf type {@code nitric.document.v1.DocumentQueryResponse}
 */
public final class DocumentQueryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nitric.document.v1.DocumentQueryResponse)
    DocumentQueryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DocumentQueryResponse.newBuilder() to construct.
  private DocumentQueryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DocumentQueryResponse() {
    documents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DocumentQueryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DocumentQueryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              documents_ = new java.util.ArrayList<io.nitric.proto.document.v1.Document>();
              mutable_bitField0_ |= 0x00000001;
            }
            documents_.add(
                input.readMessage(io.nitric.proto.document.v1.Document.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              pagingToken_ = com.google.protobuf.MapField.newMapField(
                  PagingTokenDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            pagingToken__ = input.readMessage(
                PagingTokenDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            pagingToken_.getMutableMap().put(
                pagingToken__.getKey(), pagingToken__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        documents_ = java.util.Collections.unmodifiableList(documents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nitric.proto.document.v1.Documents.internal_static_nitric_document_v1_DocumentQueryResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetPagingToken();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nitric.proto.document.v1.Documents.internal_static_nitric_document_v1_DocumentQueryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nitric.proto.document.v1.DocumentQueryResponse.class, io.nitric.proto.document.v1.DocumentQueryResponse.Builder.class);
  }

  public static final int DOCUMENTS_FIELD_NUMBER = 1;
  private java.util.List<io.nitric.proto.document.v1.Document> documents_;
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.nitric.proto.document.v1.Document> getDocumentsList() {
    return documents_;
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.nitric.proto.document.v1.DocumentOrBuilder>
      getDocumentsOrBuilderList() {
    return documents_;
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  @java.lang.Override
  public int getDocumentsCount() {
    return documents_.size();
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.document.v1.Document getDocuments(int index) {
    return documents_.get(index);
  }
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.document.v1.DocumentOrBuilder getDocumentsOrBuilder(
      int index) {
    return documents_.get(index);
  }

  public static final int PAGING_TOKEN_FIELD_NUMBER = 2;
  private static final class PagingTokenDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.nitric.proto.document.v1.Documents.internal_static_nitric_document_v1_DocumentQueryResponse_PagingTokenEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> pagingToken_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetPagingToken() {
    if (pagingToken_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PagingTokenDefaultEntryHolder.defaultEntry);
    }
    return pagingToken_;
  }

  public int getPagingTokenCount() {
    return internalGetPagingToken().getMap().size();
  }
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */

  @java.lang.Override
  public boolean containsPagingToken(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetPagingToken().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPagingTokenMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getPagingToken() {
    return getPagingTokenMap();
  }
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getPagingTokenMap() {
    return internalGetPagingToken().getMap();
  }
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getPagingTokenOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetPagingToken().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getPagingTokenOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetPagingToken().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < documents_.size(); i++) {
      output.writeMessage(1, documents_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPagingToken(),
        PagingTokenDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < documents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, documents_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetPagingToken().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      pagingToken__ = PagingTokenDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pagingToken__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nitric.proto.document.v1.DocumentQueryResponse)) {
      return super.equals(obj);
    }
    io.nitric.proto.document.v1.DocumentQueryResponse other = (io.nitric.proto.document.v1.DocumentQueryResponse) obj;

    if (!getDocumentsList()
        .equals(other.getDocumentsList())) return false;
    if (!internalGetPagingToken().equals(
        other.internalGetPagingToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDocumentsCount() > 0) {
      hash = (37 * hash) + DOCUMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getDocumentsList().hashCode();
    }
    if (!internalGetPagingToken().getMap().isEmpty()) {
      hash = (37 * hash) + PAGING_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPagingToken().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.document.v1.DocumentQueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nitric.proto.document.v1.DocumentQueryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nitric.document.v1.DocumentQueryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nitric.document.v1.DocumentQueryResponse)
      io.nitric.proto.document.v1.DocumentQueryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nitric.proto.document.v1.Documents.internal_static_nitric_document_v1_DocumentQueryResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetPagingToken();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutablePagingToken();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nitric.proto.document.v1.Documents.internal_static_nitric_document_v1_DocumentQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nitric.proto.document.v1.DocumentQueryResponse.class, io.nitric.proto.document.v1.DocumentQueryResponse.Builder.class);
    }

    // Construct using io.nitric.proto.document.v1.DocumentQueryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDocumentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (documentsBuilder_ == null) {
        documents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        documentsBuilder_.clear();
      }
      internalGetMutablePagingToken().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nitric.proto.document.v1.Documents.internal_static_nitric_document_v1_DocumentQueryResponse_descriptor;
    }

    @java.lang.Override
    public io.nitric.proto.document.v1.DocumentQueryResponse getDefaultInstanceForType() {
      return io.nitric.proto.document.v1.DocumentQueryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.nitric.proto.document.v1.DocumentQueryResponse build() {
      io.nitric.proto.document.v1.DocumentQueryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nitric.proto.document.v1.DocumentQueryResponse buildPartial() {
      io.nitric.proto.document.v1.DocumentQueryResponse result = new io.nitric.proto.document.v1.DocumentQueryResponse(this);
      int from_bitField0_ = bitField0_;
      if (documentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          documents_ = java.util.Collections.unmodifiableList(documents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.documents_ = documents_;
      } else {
        result.documents_ = documentsBuilder_.build();
      }
      result.pagingToken_ = internalGetPagingToken();
      result.pagingToken_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nitric.proto.document.v1.DocumentQueryResponse) {
        return mergeFrom((io.nitric.proto.document.v1.DocumentQueryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nitric.proto.document.v1.DocumentQueryResponse other) {
      if (other == io.nitric.proto.document.v1.DocumentQueryResponse.getDefaultInstance()) return this;
      if (documentsBuilder_ == null) {
        if (!other.documents_.isEmpty()) {
          if (documents_.isEmpty()) {
            documents_ = other.documents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDocumentsIsMutable();
            documents_.addAll(other.documents_);
          }
          onChanged();
        }
      } else {
        if (!other.documents_.isEmpty()) {
          if (documentsBuilder_.isEmpty()) {
            documentsBuilder_.dispose();
            documentsBuilder_ = null;
            documents_ = other.documents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            documentsBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDocumentsFieldBuilder() : null;
          } else {
            documentsBuilder_.addAllMessages(other.documents_);
          }
        }
      }
      internalGetMutablePagingToken().mergeFrom(
          other.internalGetPagingToken());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.nitric.proto.document.v1.DocumentQueryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.nitric.proto.document.v1.DocumentQueryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.nitric.proto.document.v1.Document> documents_ =
      java.util.Collections.emptyList();
    private void ensureDocumentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        documents_ = new java.util.ArrayList<io.nitric.proto.document.v1.Document>(documents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.nitric.proto.document.v1.Document, io.nitric.proto.document.v1.Document.Builder, io.nitric.proto.document.v1.DocumentOrBuilder> documentsBuilder_;

    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public java.util.List<io.nitric.proto.document.v1.Document> getDocumentsList() {
      if (documentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(documents_);
      } else {
        return documentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public int getDocumentsCount() {
      if (documentsBuilder_ == null) {
        return documents_.size();
      } else {
        return documentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public io.nitric.proto.document.v1.Document getDocuments(int index) {
      if (documentsBuilder_ == null) {
        return documents_.get(index);
      } else {
        return documentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder setDocuments(
        int index, io.nitric.proto.document.v1.Document value) {
      if (documentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentsIsMutable();
        documents_.set(index, value);
        onChanged();
      } else {
        documentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder setDocuments(
        int index, io.nitric.proto.document.v1.Document.Builder builderForValue) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.set(index, builderForValue.build());
        onChanged();
      } else {
        documentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder addDocuments(io.nitric.proto.document.v1.Document value) {
      if (documentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentsIsMutable();
        documents_.add(value);
        onChanged();
      } else {
        documentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder addDocuments(
        int index, io.nitric.proto.document.v1.Document value) {
      if (documentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentsIsMutable();
        documents_.add(index, value);
        onChanged();
      } else {
        documentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder addDocuments(
        io.nitric.proto.document.v1.Document.Builder builderForValue) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.add(builderForValue.build());
        onChanged();
      } else {
        documentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder addDocuments(
        int index, io.nitric.proto.document.v1.Document.Builder builderForValue) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.add(index, builderForValue.build());
        onChanged();
      } else {
        documentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder addAllDocuments(
        java.lang.Iterable<? extends io.nitric.proto.document.v1.Document> values) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, documents_);
        onChanged();
      } else {
        documentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder clearDocuments() {
      if (documentsBuilder_ == null) {
        documents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        documentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public Builder removeDocuments(int index) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.remove(index);
        onChanged();
      } else {
        documentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public io.nitric.proto.document.v1.Document.Builder getDocumentsBuilder(
        int index) {
      return getDocumentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public io.nitric.proto.document.v1.DocumentOrBuilder getDocumentsOrBuilder(
        int index) {
      if (documentsBuilder_ == null) {
        return documents_.get(index);  } else {
        return documentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public java.util.List<? extends io.nitric.proto.document.v1.DocumentOrBuilder>
         getDocumentsOrBuilderList() {
      if (documentsBuilder_ != null) {
        return documentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(documents_);
      }
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public io.nitric.proto.document.v1.Document.Builder addDocumentsBuilder() {
      return getDocumentsFieldBuilder().addBuilder(
          io.nitric.proto.document.v1.Document.getDefaultInstance());
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public io.nitric.proto.document.v1.Document.Builder addDocumentsBuilder(
        int index) {
      return getDocumentsFieldBuilder().addBuilder(
          index, io.nitric.proto.document.v1.Document.getDefaultInstance());
    }
    /**
     * <pre>
     * The retrieved values
     * </pre>
     *
     * <code>repeated .nitric.document.v1.Document documents = 1;</code>
     */
    public java.util.List<io.nitric.proto.document.v1.Document.Builder>
         getDocumentsBuilderList() {
      return getDocumentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.nitric.proto.document.v1.Document, io.nitric.proto.document.v1.Document.Builder, io.nitric.proto.document.v1.DocumentOrBuilder>
        getDocumentsFieldBuilder() {
      if (documentsBuilder_ == null) {
        documentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.nitric.proto.document.v1.Document, io.nitric.proto.document.v1.Document.Builder, io.nitric.proto.document.v1.DocumentOrBuilder>(
                documents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        documents_ = null;
      }
      return documentsBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> pagingToken_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetPagingToken() {
      if (pagingToken_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PagingTokenDefaultEntryHolder.defaultEntry);
      }
      return pagingToken_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutablePagingToken() {
      onChanged();;
      if (pagingToken_ == null) {
        pagingToken_ = com.google.protobuf.MapField.newMapField(
            PagingTokenDefaultEntryHolder.defaultEntry);
      }
      if (!pagingToken_.isMutable()) {
        pagingToken_ = pagingToken_.copy();
      }
      return pagingToken_;
    }

    public int getPagingTokenCount() {
      return internalGetPagingToken().getMap().size();
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */

    @java.lang.Override
    public boolean containsPagingToken(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPagingToken().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPagingTokenMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getPagingToken() {
      return getPagingTokenMap();
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getPagingTokenMap() {
      return internalGetPagingToken().getMap();
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getPagingTokenOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPagingToken().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getPagingTokenOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetPagingToken().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPagingToken() {
      internalGetMutablePagingToken().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */

    public Builder removePagingToken(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePagingToken().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutablePagingToken() {
      return internalGetMutablePagingToken().getMutableMap();
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */
    public Builder putPagingToken(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePagingToken().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * The query paging continuation token, when empty no further results are available
     * </pre>
     *
     * <code>map&lt;string, string&gt; paging_token = 2;</code>
     */

    public Builder putAllPagingToken(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutablePagingToken().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nitric.document.v1.DocumentQueryResponse)
  }

  // @@protoc_insertion_point(class_scope:nitric.document.v1.DocumentQueryResponse)
  private static final io.nitric.proto.document.v1.DocumentQueryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nitric.proto.document.v1.DocumentQueryResponse();
  }

  public static io.nitric.proto.document.v1.DocumentQueryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DocumentQueryResponse>
      PARSER = new com.google.protobuf.AbstractParser<DocumentQueryResponse>() {
    @java.lang.Override
    public DocumentQueryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DocumentQueryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DocumentQueryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DocumentQueryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nitric.proto.document.v1.DocumentQueryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

