// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: document/v1/document.proto

package io.nitric.proto.document.v1;

public interface DocumentQueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.document.v1.DocumentQueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  java.util.List<io.nitric.proto.document.v1.Document>
      getDocumentsList();
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  io.nitric.proto.document.v1.Document getDocuments(int index);
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  int getDocumentsCount();
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  java.util.List<? extends io.nitric.proto.document.v1.DocumentOrBuilder>
      getDocumentsOrBuilderList();
  /**
   * <pre>
   * The retrieved values
   * </pre>
   *
   * <code>repeated .nitric.document.v1.Document documents = 1;</code>
   */
  io.nitric.proto.document.v1.DocumentOrBuilder getDocumentsOrBuilder(
      int index);

  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */
  int getPagingTokenCount();
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */
  boolean containsPagingToken(
      java.lang.String key);
  /**
   * Use {@link #getPagingTokenMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getPagingToken();
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPagingTokenMap();
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */

  java.lang.String getPagingTokenOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * The query paging continuation token, when empty no further results are available
   * </pre>
   *
   * <code>map&lt;string, string&gt; paging_token = 2;</code>
   */

  java.lang.String getPagingTokenOrThrow(
      java.lang.String key);
}
