// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: document/v1/document.proto

package io.nitric.proto.document.v1;

public interface DocumentDeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.document.v1.DocumentDeleteResponse)
    com.google.protobuf.MessageOrBuilder {
}
