// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public interface HttpResponseContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.faas.v1.HttpResponseContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The request headers...
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  int getHeadersCount();
  /**
   * <pre>
   * The request headers...
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  boolean containsHeaders(
      java.lang.String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaders();
  /**
   * <pre>
   * The request headers...
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeadersMap();
  /**
   * <pre>
   * The request headers...
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */

  java.lang.String getHeadersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * The request headers...
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */

  java.lang.String getHeadersOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * The HTTP status of the request
   * </pre>
   *
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
