// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public final class NitricFaas {
  private NitricFaas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ClientMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ServerMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_InitRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_InitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_InitResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_InitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TriggerRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TopicTriggerContext_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TopicTriggerContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TriggerResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TriggerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpResponseContext_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpResponseContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TopicResponseContext_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TopicResponseContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022faas/v1/faas.proto\022\016nitric.faas.v1\"\230\001\n" +
      "\rClientMessage\022\n\n\002id\030\001 \001(\t\0223\n\014init_reque" +
      "st\030\002 \001(\0132\033.nitric.faas.v1.InitRequestH\000\022" +
      ";\n\020trigger_response\030\003 \001(\0132\037.nitric.faas." +
      "v1.TriggerResponseH\000B\t\n\007content\"\230\001\n\rServ" +
      "erMessage\022\n\n\002id\030\001 \001(\t\0225\n\rinit_response\030\002" +
      " \001(\0132\034.nitric.faas.v1.InitResponseH\000\0229\n\017" +
      "trigger_request\030\003 \001(\0132\036.nitric.faas.v1.T" +
      "riggerRequestH\000B\t\n\007content\"\r\n\013InitReques" +
      "t\"\016\n\014InitResponse\"\246\001\n\016TriggerRequest\022\014\n\004" +
      "data\030\001 \001(\014\022\021\n\tmime_type\030\002 \001(\t\0222\n\004http\030\003 " +
      "\001(\0132\".nitric.faas.v1.HttpTriggerContextH" +
      "\000\0224\n\005topic\030\004 \001(\0132#.nitric.faas.v1.TopicT" +
      "riggerContextH\000B\t\n\007context\"\243\002\n\022HttpTrigg" +
      "erContext\022\016\n\006method\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\022" +
      "@\n\007headers\030\003 \003(\0132/.nitric.faas.v1.HttpTr" +
      "iggerContext.HeadersEntry\022I\n\014query_param" +
      "s\030\004 \003(\01323.nitric.faas.v1.HttpTriggerCont" +
      "ext.QueryParamsEntry\032.\n\014HeadersEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0322\n\020QueryPar" +
      "amsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "\"$\n\023TopicTriggerContext\022\r\n\005topic\030\001 \001(\t\"\226" +
      "\001\n\017TriggerResponse\022\014\n\004data\030\001 \001(\014\0223\n\004http" +
      "\030\n \001(\0132#.nitric.faas.v1.HttpResponseCont" +
      "extH\000\0225\n\005topic\030\013 \001(\0132$.nitric.faas.v1.To" +
      "picResponseContextH\000B\t\n\007context\"\230\001\n\023Http" +
      "ResponseContext\022A\n\007headers\030\001 \003(\01320.nitri" +
      "c.faas.v1.HttpResponseContext.HeadersEnt" +
      "ry\022\016\n\006status\030\002 \001(\005\032.\n\014HeadersEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\'\n\024TopicRespo" +
      "nseContext\022\017\n\007success\030\001 \001(\0102Y\n\004Faas\022Q\n\rT" +
      "riggerStream\022\035.nitric.faas.v1.ClientMess" +
      "age\032\035.nitric.faas.v1.ServerMessage(\0010\001Bc" +
      "\n\027io.nitric.proto.faas.v1B\nNitricFaasP\001Z" +
      "\014nitric/v1;v1\252\002\024Nitric.Proto.Faas.v1\312\002\024N" +
      "itric\\Proto\\Faas\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nitric_faas_v1_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nitric_faas_v1_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ClientMessage_descriptor,
        new java.lang.String[] { "Id", "InitRequest", "TriggerResponse", "Content", });
    internal_static_nitric_faas_v1_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nitric_faas_v1_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ServerMessage_descriptor,
        new java.lang.String[] { "Id", "InitResponse", "TriggerRequest", "Content", });
    internal_static_nitric_faas_v1_InitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nitric_faas_v1_InitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_InitRequest_descriptor,
        new java.lang.String[] { });
    internal_static_nitric_faas_v1_InitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nitric_faas_v1_InitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_InitResponse_descriptor,
        new java.lang.String[] { });
    internal_static_nitric_faas_v1_TriggerRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nitric_faas_v1_TriggerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TriggerRequest_descriptor,
        new java.lang.String[] { "Data", "MimeType", "Http", "Topic", "Context", });
    internal_static_nitric_faas_v1_HttpTriggerContext_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nitric_faas_v1_HttpTriggerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_descriptor,
        new java.lang.String[] { "Method", "Path", "Headers", "QueryParams", });
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(0);
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(1);
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_TopicTriggerContext_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_nitric_faas_v1_TopicTriggerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TopicTriggerContext_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_nitric_faas_v1_TriggerResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_nitric_faas_v1_TriggerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TriggerResponse_descriptor,
        new java.lang.String[] { "Data", "Http", "Topic", "Context", });
    internal_static_nitric_faas_v1_HttpResponseContext_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_nitric_faas_v1_HttpResponseContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpResponseContext_descriptor,
        new java.lang.String[] { "Headers", "Status", });
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_descriptor =
      internal_static_nitric_faas_v1_HttpResponseContext_descriptor.getNestedTypes().get(0);
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_TopicResponseContext_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_nitric_faas_v1_TopicResponseContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TopicResponseContext_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
