// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: faas/v1/faas.proto

package io.nitric.proto.faas.v1;

/**
 * <pre>
 * Messages the server is able to send to the client
 * </pre>
 *
 * Protobuf type {@code nitric.faas.v1.ServerMessage}
 */
public final class ServerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nitric.faas.v1.ServerMessage)
    ServerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerMessage.newBuilder() to construct.
  private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerMessage() {
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            io.nitric.proto.faas.v1.InitResponse.Builder subBuilder = null;
            if (contentCase_ == 2) {
              subBuilder = ((io.nitric.proto.faas.v1.InitResponse) content_).toBuilder();
            }
            content_ =
                input.readMessage(io.nitric.proto.faas.v1.InitResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.faas.v1.InitResponse) content_);
              content_ = subBuilder.buildPartial();
            }
            contentCase_ = 2;
            break;
          }
          case 26: {
            io.nitric.proto.faas.v1.TriggerRequest.Builder subBuilder = null;
            if (contentCase_ == 3) {
              subBuilder = ((io.nitric.proto.faas.v1.TriggerRequest) content_).toBuilder();
            }
            content_ =
                input.readMessage(io.nitric.proto.faas.v1.TriggerRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.faas.v1.TriggerRequest) content_);
              content_ = subBuilder.buildPartial();
            }
            contentCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nitric.proto.faas.v1.NitricFaas.internal_static_nitric_faas_v1_ServerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nitric.proto.faas.v1.NitricFaas.internal_static_nitric_faas_v1_ServerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nitric.proto.faas.v1.ServerMessage.class, io.nitric.proto.faas.v1.ServerMessage.Builder.class);
  }

  private int contentCase_ = 0;
  private java.lang.Object content_;
  public enum ContentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INIT_RESPONSE(2),
    TRIGGER_REQUEST(3),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 2: return INIT_RESPONSE;
        case 3: return TRIGGER_REQUEST;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Server message ID, used to pair requests/responses
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Server message ID, used to pair requests/responses
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INIT_RESPONSE_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Server responding
   * with client configuration details to an
   * InitRequest
   * </pre>
   *
   * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
   * @return Whether the initResponse field is set.
   */
  @java.lang.Override
  public boolean hasInitResponse() {
    return contentCase_ == 2;
  }
  /**
   * <pre>
   * Server responding
   * with client configuration details to an
   * InitRequest
   * </pre>
   *
   * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
   * @return The initResponse.
   */
  @java.lang.Override
  public io.nitric.proto.faas.v1.InitResponse getInitResponse() {
    if (contentCase_ == 2) {
       return (io.nitric.proto.faas.v1.InitResponse) content_;
    }
    return io.nitric.proto.faas.v1.InitResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * Server responding
   * with client configuration details to an
   * InitRequest
   * </pre>
   *
   * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
   */
  @java.lang.Override
  public io.nitric.proto.faas.v1.InitResponseOrBuilder getInitResponseOrBuilder() {
    if (contentCase_ == 2) {
       return (io.nitric.proto.faas.v1.InitResponse) content_;
    }
    return io.nitric.proto.faas.v1.InitResponse.getDefaultInstance();
  }

  public static final int TRIGGER_REQUEST_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Server requesting client to
   * process a trigger
   * </pre>
   *
   * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
   * @return Whether the triggerRequest field is set.
   */
  @java.lang.Override
  public boolean hasTriggerRequest() {
    return contentCase_ == 3;
  }
  /**
   * <pre>
   * Server requesting client to
   * process a trigger
   * </pre>
   *
   * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
   * @return The triggerRequest.
   */
  @java.lang.Override
  public io.nitric.proto.faas.v1.TriggerRequest getTriggerRequest() {
    if (contentCase_ == 3) {
       return (io.nitric.proto.faas.v1.TriggerRequest) content_;
    }
    return io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * Server requesting client to
   * process a trigger
   * </pre>
   *
   * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
   */
  @java.lang.Override
  public io.nitric.proto.faas.v1.TriggerRequestOrBuilder getTriggerRequestOrBuilder() {
    if (contentCase_ == 3) {
       return (io.nitric.proto.faas.v1.TriggerRequest) content_;
    }
    return io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (contentCase_ == 2) {
      output.writeMessage(2, (io.nitric.proto.faas.v1.InitResponse) content_);
    }
    if (contentCase_ == 3) {
      output.writeMessage(3, (io.nitric.proto.faas.v1.TriggerRequest) content_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (contentCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.nitric.proto.faas.v1.InitResponse) content_);
    }
    if (contentCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.nitric.proto.faas.v1.TriggerRequest) content_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nitric.proto.faas.v1.ServerMessage)) {
      return super.equals(obj);
    }
    io.nitric.proto.faas.v1.ServerMessage other = (io.nitric.proto.faas.v1.ServerMessage) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getContentCase().equals(other.getContentCase())) return false;
    switch (contentCase_) {
      case 2:
        if (!getInitResponse()
            .equals(other.getInitResponse())) return false;
        break;
      case 3:
        if (!getTriggerRequest()
            .equals(other.getTriggerRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    switch (contentCase_) {
      case 2:
        hash = (37 * hash) + INIT_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getInitResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + TRIGGER_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getTriggerRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.faas.v1.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nitric.proto.faas.v1.ServerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Messages the server is able to send to the client
   * </pre>
   *
   * Protobuf type {@code nitric.faas.v1.ServerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nitric.faas.v1.ServerMessage)
      io.nitric.proto.faas.v1.ServerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nitric.proto.faas.v1.NitricFaas.internal_static_nitric_faas_v1_ServerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nitric.proto.faas.v1.NitricFaas.internal_static_nitric_faas_v1_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nitric.proto.faas.v1.ServerMessage.class, io.nitric.proto.faas.v1.ServerMessage.Builder.class);
    }

    // Construct using io.nitric.proto.faas.v1.ServerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      contentCase_ = 0;
      content_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nitric.proto.faas.v1.NitricFaas.internal_static_nitric_faas_v1_ServerMessage_descriptor;
    }

    @java.lang.Override
    public io.nitric.proto.faas.v1.ServerMessage getDefaultInstanceForType() {
      return io.nitric.proto.faas.v1.ServerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.nitric.proto.faas.v1.ServerMessage build() {
      io.nitric.proto.faas.v1.ServerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nitric.proto.faas.v1.ServerMessage buildPartial() {
      io.nitric.proto.faas.v1.ServerMessage result = new io.nitric.proto.faas.v1.ServerMessage(this);
      result.id_ = id_;
      if (contentCase_ == 2) {
        if (initResponseBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = initResponseBuilder_.build();
        }
      }
      if (contentCase_ == 3) {
        if (triggerRequestBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = triggerRequestBuilder_.build();
        }
      }
      result.contentCase_ = contentCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nitric.proto.faas.v1.ServerMessage) {
        return mergeFrom((io.nitric.proto.faas.v1.ServerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nitric.proto.faas.v1.ServerMessage other) {
      if (other == io.nitric.proto.faas.v1.ServerMessage.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      switch (other.getContentCase()) {
        case INIT_RESPONSE: {
          mergeInitResponse(other.getInitResponse());
          break;
        }
        case TRIGGER_REQUEST: {
          mergeTriggerRequest(other.getTriggerRequest());
          break;
        }
        case CONTENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.nitric.proto.faas.v1.ServerMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.nitric.proto.faas.v1.ServerMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int contentCase_ = 0;
    private java.lang.Object content_;
    public ContentCase
        getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public Builder clearContent() {
      contentCase_ = 0;
      content_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Server message ID, used to pair requests/responses
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Server message ID, used to pair requests/responses
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Server message ID, used to pair requests/responses
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Server message ID, used to pair requests/responses
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {

      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Server message ID, used to pair requests/responses
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.faas.v1.InitResponse, io.nitric.proto.faas.v1.InitResponse.Builder, io.nitric.proto.faas.v1.InitResponseOrBuilder> initResponseBuilder_;
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     * @return Whether the initResponse field is set.
     */
    @java.lang.Override
    public boolean hasInitResponse() {
      return contentCase_ == 2;
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     * @return The initResponse.
     */
    @java.lang.Override
    public io.nitric.proto.faas.v1.InitResponse getInitResponse() {
      if (initResponseBuilder_ == null) {
        if (contentCase_ == 2) {
          return (io.nitric.proto.faas.v1.InitResponse) content_;
        }
        return io.nitric.proto.faas.v1.InitResponse.getDefaultInstance();
      } else {
        if (contentCase_ == 2) {
          return initResponseBuilder_.getMessage();
        }
        return io.nitric.proto.faas.v1.InitResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    public Builder setInitResponse(io.nitric.proto.faas.v1.InitResponse value) {
      if (initResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        initResponseBuilder_.setMessage(value);
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    public Builder setInitResponse(
        io.nitric.proto.faas.v1.InitResponse.Builder builderForValue) {
      if (initResponseBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        initResponseBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    public Builder mergeInitResponse(io.nitric.proto.faas.v1.InitResponse value) {
      if (initResponseBuilder_ == null) {
        if (contentCase_ == 2 &&
            content_ != io.nitric.proto.faas.v1.InitResponse.getDefaultInstance()) {
          content_ = io.nitric.proto.faas.v1.InitResponse.newBuilder((io.nitric.proto.faas.v1.InitResponse) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 2) {
          initResponseBuilder_.mergeFrom(value);
        }
        initResponseBuilder_.setMessage(value);
      }
      contentCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    public Builder clearInitResponse() {
      if (initResponseBuilder_ == null) {
        if (contentCase_ == 2) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 2) {
          contentCase_ = 0;
          content_ = null;
        }
        initResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    public io.nitric.proto.faas.v1.InitResponse.Builder getInitResponseBuilder() {
      return getInitResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    @java.lang.Override
    public io.nitric.proto.faas.v1.InitResponseOrBuilder getInitResponseOrBuilder() {
      if ((contentCase_ == 2) && (initResponseBuilder_ != null)) {
        return initResponseBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 2) {
          return (io.nitric.proto.faas.v1.InitResponse) content_;
        }
        return io.nitric.proto.faas.v1.InitResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Server responding
     * with client configuration details to an
     * InitRequest
     * </pre>
     *
     * <code>.nitric.faas.v1.InitResponse init_response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.faas.v1.InitResponse, io.nitric.proto.faas.v1.InitResponse.Builder, io.nitric.proto.faas.v1.InitResponseOrBuilder>
        getInitResponseFieldBuilder() {
      if (initResponseBuilder_ == null) {
        if (!(contentCase_ == 2)) {
          content_ = io.nitric.proto.faas.v1.InitResponse.getDefaultInstance();
        }
        initResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.faas.v1.InitResponse, io.nitric.proto.faas.v1.InitResponse.Builder, io.nitric.proto.faas.v1.InitResponseOrBuilder>(
                (io.nitric.proto.faas.v1.InitResponse) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 2;
      onChanged();;
      return initResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.faas.v1.TriggerRequest, io.nitric.proto.faas.v1.TriggerRequest.Builder, io.nitric.proto.faas.v1.TriggerRequestOrBuilder> triggerRequestBuilder_;
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     * @return Whether the triggerRequest field is set.
     */
    @java.lang.Override
    public boolean hasTriggerRequest() {
      return contentCase_ == 3;
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     * @return The triggerRequest.
     */
    @java.lang.Override
    public io.nitric.proto.faas.v1.TriggerRequest getTriggerRequest() {
      if (triggerRequestBuilder_ == null) {
        if (contentCase_ == 3) {
          return (io.nitric.proto.faas.v1.TriggerRequest) content_;
        }
        return io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance();
      } else {
        if (contentCase_ == 3) {
          return triggerRequestBuilder_.getMessage();
        }
        return io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    public Builder setTriggerRequest(io.nitric.proto.faas.v1.TriggerRequest value) {
      if (triggerRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        triggerRequestBuilder_.setMessage(value);
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    public Builder setTriggerRequest(
        io.nitric.proto.faas.v1.TriggerRequest.Builder builderForValue) {
      if (triggerRequestBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        triggerRequestBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    public Builder mergeTriggerRequest(io.nitric.proto.faas.v1.TriggerRequest value) {
      if (triggerRequestBuilder_ == null) {
        if (contentCase_ == 3 &&
            content_ != io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance()) {
          content_ = io.nitric.proto.faas.v1.TriggerRequest.newBuilder((io.nitric.proto.faas.v1.TriggerRequest) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 3) {
          triggerRequestBuilder_.mergeFrom(value);
        }
        triggerRequestBuilder_.setMessage(value);
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    public Builder clearTriggerRequest() {
      if (triggerRequestBuilder_ == null) {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
        }
        triggerRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    public io.nitric.proto.faas.v1.TriggerRequest.Builder getTriggerRequestBuilder() {
      return getTriggerRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    @java.lang.Override
    public io.nitric.proto.faas.v1.TriggerRequestOrBuilder getTriggerRequestOrBuilder() {
      if ((contentCase_ == 3) && (triggerRequestBuilder_ != null)) {
        return triggerRequestBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 3) {
          return (io.nitric.proto.faas.v1.TriggerRequest) content_;
        }
        return io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Server requesting client to
     * process a trigger
     * </pre>
     *
     * <code>.nitric.faas.v1.TriggerRequest trigger_request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.faas.v1.TriggerRequest, io.nitric.proto.faas.v1.TriggerRequest.Builder, io.nitric.proto.faas.v1.TriggerRequestOrBuilder>
        getTriggerRequestFieldBuilder() {
      if (triggerRequestBuilder_ == null) {
        if (!(contentCase_ == 3)) {
          content_ = io.nitric.proto.faas.v1.TriggerRequest.getDefaultInstance();
        }
        triggerRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.faas.v1.TriggerRequest, io.nitric.proto.faas.v1.TriggerRequest.Builder, io.nitric.proto.faas.v1.TriggerRequestOrBuilder>(
                (io.nitric.proto.faas.v1.TriggerRequest) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 3;
      onChanged();;
      return triggerRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nitric.faas.v1.ServerMessage)
  }

  // @@protoc_insertion_point(class_scope:nitric.faas.v1.ServerMessage)
  private static final io.nitric.proto.faas.v1.ServerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nitric.proto.faas.v1.ServerMessage();
  }

  public static io.nitric.proto.faas.v1.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMessage>
      PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
    @java.lang.Override
    public ServerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nitric.proto.faas.v1.ServerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

