// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public interface TopicTriggerContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.faas.v1.TopicTriggerContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The topic the message was published for
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * The topic the message was published for
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
