// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage/v1/storage.proto

package io.nitric.proto.storage.v1;

public interface StorageReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.storage.v1.StorageReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The body bytes of the retrieved storage item
   * </pre>
   *
   * <code>bytes body = 1;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
