// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue/v1/queue.proto

package io.nitric.proto.queue.v1;

/*-
 * #%L
 * Nitric Java SDK
 * %%
 * Copyright (C) 2021 Nitric Pty Ltd
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

public interface QueueCompleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.queue.v1.QueueCompleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The nitric name for the queue
   *  this will automatically be resolved to the provider specific queue identifier.
   * </pre>
   *
   * <code>string queue = 1;</code>
   * @return The queue.
   */
  java.lang.String getQueue();
  /**
   * <pre>
   * The nitric name for the queue
   *  this will automatically be resolved to the provider specific queue identifier.
   * </pre>
   *
   * <code>string queue = 1;</code>
   * @return The bytes for queue.
   */
  com.google.protobuf.ByteString
      getQueueBytes();

  /**
   * <pre>
   * Lease id of the task to be completed
   * </pre>
   *
   * <code>string leaseId = 2;</code>
   * @return The leaseId.
   */
  java.lang.String getLeaseId();
  /**
   * <pre>
   * Lease id of the task to be completed
   * </pre>
   *
   * <code>string leaseId = 2;</code>
   * @return The bytes for leaseId.
   */
  com.google.protobuf.ByteString
      getLeaseIdBytes();
}
