// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue/v1/queue.proto

package io.nitric.proto.queue.v1;

/*-
 * #%L
 * Nitric Java SDK
 * %%
 * Copyright (C) 2021 Nitric Pty Ltd
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

public final class Queues {
  private Queues() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueSendRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueSendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueSendResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueSendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueSendBatchRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueSendBatchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueSendBatchResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueSendBatchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueReceiveRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueReceiveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueReceiveResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueReceiveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueCompleteRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueCompleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_QueueCompleteResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_QueueCompleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_FailedTask_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_FailedTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_queue_v1_NitricTask_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_queue_v1_NitricTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024queue/v1/queue.proto\022\017nitric.queue.v1\032" +
      "\034google/protobuf/struct.proto\"L\n\020QueueSe" +
      "ndRequest\022\r\n\005queue\030\001 \001(\t\022)\n\004task\030\002 \001(\0132\033" +
      ".nitric.queue.v1.NitricTask\"\023\n\021QueueSend" +
      "Response\"R\n\025QueueSendBatchRequest\022\r\n\005que" +
      "ue\030\001 \001(\t\022*\n\005tasks\030\002 \003(\0132\033.nitric.queue.v" +
      "1.NitricTask\"J\n\026QueueSendBatchResponse\0220" +
      "\n\013failedTasks\030\001 \003(\0132\033.nitric.queue.v1.Fa" +
      "iledTask\"3\n\023QueueReceiveRequest\022\r\n\005queue" +
      "\030\001 \001(\t\022\r\n\005depth\030\002 \001(\005\"B\n\024QueueReceiveRes" +
      "ponse\022*\n\005tasks\030\001 \003(\0132\033.nitric.queue.v1.N" +
      "itricTask\"6\n\024QueueCompleteRequest\022\r\n\005que" +
      "ue\030\001 \001(\t\022\017\n\007leaseId\030\002 \001(\t\"\027\n\025QueueComple" +
      "teResponse\"H\n\nFailedTask\022)\n\004task\030\001 \001(\0132\033" +
      ".nitric.queue.v1.NitricTask\022\017\n\007message\030\002" +
      " \001(\t\"h\n\nNitricTask\022\n\n\002id\030\001 \001(\t\022\017\n\007leaseI" +
      "d\030\002 \001(\t\022\023\n\013payloadType\030\003 \001(\t\022(\n\007payload\030" +
      "\004 \001(\0132\027.google.protobuf.Struct2\347\002\n\005Queue" +
      "\022M\n\004Send\022!.nitric.queue.v1.QueueSendRequ" +
      "est\032\".nitric.queue.v1.QueueSendResponse\022" +
      "\\\n\tSendBatch\022&.nitric.queue.v1.QueueSend" +
      "BatchRequest\032\'.nitric.queue.v1.QueueSend" +
      "BatchResponse\022V\n\007Receive\022$.nitric.queue." +
      "v1.QueueReceiveRequest\032%.nitric.queue.v1" +
      ".QueueReceiveResponse\022Y\n\010Complete\022%.nitr" +
      "ic.queue.v1.QueueCompleteRequest\032&.nitri" +
      "c.queue.v1.QueueCompleteResponseBb\n\030io.n" +
      "itric.proto.queue.v1B\006QueuesP\001Z\014nitric/v" +
      "1;v1\252\002\025Nitric.Proto.Queue.v1\312\002\025Nitric\\Pr" +
      "oto\\Queue\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_nitric_queue_v1_QueueSendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nitric_queue_v1_QueueSendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueSendRequest_descriptor,
        new java.lang.String[] { "Queue", "Task", });
    internal_static_nitric_queue_v1_QueueSendResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nitric_queue_v1_QueueSendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueSendResponse_descriptor,
        new java.lang.String[] { });
    internal_static_nitric_queue_v1_QueueSendBatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nitric_queue_v1_QueueSendBatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueSendBatchRequest_descriptor,
        new java.lang.String[] { "Queue", "Tasks", });
    internal_static_nitric_queue_v1_QueueSendBatchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nitric_queue_v1_QueueSendBatchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueSendBatchResponse_descriptor,
        new java.lang.String[] { "FailedTasks", });
    internal_static_nitric_queue_v1_QueueReceiveRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nitric_queue_v1_QueueReceiveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueReceiveRequest_descriptor,
        new java.lang.String[] { "Queue", "Depth", });
    internal_static_nitric_queue_v1_QueueReceiveResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nitric_queue_v1_QueueReceiveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueReceiveResponse_descriptor,
        new java.lang.String[] { "Tasks", });
    internal_static_nitric_queue_v1_QueueCompleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_nitric_queue_v1_QueueCompleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueCompleteRequest_descriptor,
        new java.lang.String[] { "Queue", "LeaseId", });
    internal_static_nitric_queue_v1_QueueCompleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_nitric_queue_v1_QueueCompleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_QueueCompleteResponse_descriptor,
        new java.lang.String[] { });
    internal_static_nitric_queue_v1_FailedTask_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_nitric_queue_v1_FailedTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_FailedTask_descriptor,
        new java.lang.String[] { "Task", "Message", });
    internal_static_nitric_queue_v1_NitricTask_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_nitric_queue_v1_NitricTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_queue_v1_NitricTask_descriptor,
        new java.lang.String[] { "Id", "LeaseId", "PayloadType", "Payload", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
