// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue/v1/queue.proto

package io.nitric.proto.queue.v1;

public interface QueueSendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.queue.v1.QueueSendResponse)
    com.google.protobuf.MessageOrBuilder {
}
