// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue/v1/queue.proto

package io.nitric.proto.queue.v1;

public interface QueueCompleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.queue.v1.QueueCompleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The nitric name for the queue
   *  this will automatically be resolved to the provider specific queue identifier.
   * </pre>
   *
   * <code>string queue = 1;</code>
   * @return The queue.
   */
  java.lang.String getQueue();
  /**
   * <pre>
   * The nitric name for the queue
   *  this will automatically be resolved to the provider specific queue identifier.
   * </pre>
   *
   * <code>string queue = 1;</code>
   * @return The bytes for queue.
   */
  com.google.protobuf.ByteString
      getQueueBytes();

  /**
   * <pre>
   * Lease id of the task to be completed
   * </pre>
   *
   * <code>string lease_id = 2;</code>
   * @return The leaseId.
   */
  java.lang.String getLeaseId();
  /**
   * <pre>
   * Lease id of the task to be completed
   * </pre>
   *
   * <code>string lease_id = 2;</code>
   * @return The bytes for leaseId.
   */
  com.google.protobuf.ByteString
      getLeaseIdBytes();
}
