// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/v1/auth.proto

package io.nitric.proto.auth.v1;

public interface UserCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.auth.v1.UserCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
